export const GET_WHEATHER = "GET_WHEATHER";
export const RESET_WHEATHER = "RESET_WHEATHER";
export const GET_EVENTS = "GET_EVENTS";
export const GET_EVENT = "GET_EVENT";
export const RESET_EVENTS = "RESET_EVENTS";
export const RESET_EVENT = "RESET_EVENT";
export const GET_WHEATHER_REQUESTED = "GET_WHEATHER_REQUESTED";
export const RESET_WHEATHER_REQUESTED = "RESET_WHEATHER_REQUESTED";
export const GET_EVENTS_REQUESTED = "GET_EVENTS_REQUESTED";
export const RESET_EVENTS_REQUESTED = "RESET_EVENTS_REQUESTED";

